version: '3.8'

volumes:
  wordpress:
    name: ${PREFIX}-wordpress
  database:
    name: ${PREFIX}-db
  flags:
    name: ${PREFIX}-flags

services:
  setup:
    image: brainfood/setup
    build:
      context: ./setup
    environment:
      MYSQL_HOST: mariadb
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      RESTIC_URL: ${RESTIC_URL}
    links:
      - mariadb
    secrets:
      - aws-access-key-id
      - aws-secret-access-key
      - mysql-password
      - mysql-root-password
      - restic-password
    volumes:
      - wordpress:/var/www/html
      - flags:/var/run/bfflags

  mariadb:
    image: mariadb
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD_FILE: /run/secrets/mysql-password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql-root-password
    secrets:
      - mysql-password
      - mysql-root-password
    volumes:
      - database:/var/lib/mysql

  wpcli:
    image: wordpress:cli
    environment:
      VIRTUAL_HOST: ${HOSTNAME}
      LETSENCRYPT_HOST: ${HOSTNAME}
      LETSENCRYPT_EMAIL: ${LETSENCRYPTEMAIL}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/mysql-password
    secrets:
      - mysql-password
    volumes:
      - ./setup/flagwait.sh:/usr/local/bin/flagwait.sh
      - wordpress:/var/www/html
      - flags:/var/run/bfflags

  wordpress:
    image: wordpress
    entrypoint: [ "bash", "-c", "flagwait.sh loaded && /usr/local/bin/docker-entrypoint.sh apache2-foreground"]
    environment:
      VIRTUAL_HOST: ${HOSTNAME}
      LETSENCRYPT_HOST: ${HOSTNAME}
      LETSENCRYPT_EMAIL: ${LETSENCRYPTEMAIL}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/mysql-password
    secrets:
      - mysql-password
    volumes:
      - ./setup/flagwait.sh:/usr/local/bin/flagwait.sh
      - wordpress:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini 
      - flags:/var/run/bfflags

secrets:
  mysql-password:
    file: ./secrets/mysql-password.txt
  mysql-root-password:
    file: ./secrets/mysql-root-password.txt
  restic-password:
    file: ./secrets/restic-password.txt
  aws-access-key-id:
    file: ./secrets/aws-access-key-id.txt
  aws-secret-access-key:
    file: ./secrets/aws-secret-access-key.txt
