version: '3.8'

networks:
  nginx:
    external:
      name: nginx
  app:

volumes:
  wordpress:
    name: ${PREFIX}-wordpress
  wordpress-conf:
    name: ${PREFIX}-wordpress-conf
  database:
    name: ${PREFIX}-db
  flags:
    name: ${PREFIX}-flags
  restic:
    name: ${PREFIX}-restic

services:
  setup:
    image: brainfood/setup
    build:
      context: ./setup
    environment:
      MYSQL_HOST: mariadb
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD_FILE: /run/secrets/mysql-password
      RESTIC_REPOSITORY:
      RESTIC_HOST:
    networks:
      app:
    secrets:
      - aws-access-key-id
      - aws-secret-access-key
      - mysql-password
      - mysql-root-password
      - restic-password
    volumes:
      - ./parts/restore-db.sh:/srv/bfsetup/parts/restore-db.sh
      - restic:/root/.cache/restic
      - wordpress:/var/www/html
      - wordpress-conf:/var/www/etc
      - flags:/var/run/bfflags

  mariadb:
    image: mariadb
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD_FILE: /run/secrets/mysql-password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql-root-password
    secrets:
      - mysql-password
      - mysql-root-password
    networks:
      app:
    volumes:
      - database:/var/lib/mysql

  wpcli:
    image: wordpress:cli
    environment:
      VIRTUAL_HOST: ${HOSTNAME}
      TARGET_PROTOCOL:
      FROM_SITES:
      #LETSENCRYPT_HOST: ${HOSTNAME}
      #LETSENCRYPT_EMAIL: ${LETSENCRYPTEMAIL}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/mysql-password
    entrypoint: [ "bash", "-c", "flagwait.sh loaded && /usr/local/bin/change-site-name.sh && /usr/local/bin/docker-entrypoint.sh wp shell"]
    secrets:
      - mysql-password
    networks:
      app:
    volumes:
      - ./parts/change-site-name.sh:/usr/local/bin/change-site-name.sh
      - ./setup/flagwait.sh:/usr/local/bin/flagwait.sh
      - wordpress:/var/www/html
      - wordpress-conf:/var/www/etc
      - flags:/var/run/bfflags

  wordpress:
    image: wordpress:php7.3-apache
    entrypoint: [ "bash", "-c", "flagwait.sh setup && /usr/local/bin/docker-entrypoint.sh apache2-foreground"]
    environment:
      VIRTUAL_HOST: ${HOSTNAME}
      #LETSENCRYPT_HOST: ${HOSTNAME}
      #LETSENCRYPT_EMAIL: ${LETSENCRYPTEMAIL}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/mysql-password
    networks:
      nginx:
      app:
    secrets:
      - mysql-password
    volumes:
      - ./setup/flagwait.sh:/usr/local/bin/flagwait.sh
      - wordpress:/var/www/html
      - wordpress-conf:/var/www/etc
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini 
      - flags:/var/run/bfflags

secrets:
  mysql-password:
    file: ./secrets/mysql-password.txt
  mysql-root-password:
    file: ./secrets/mysql-root-password.txt
  restic-password:
    file: ./secrets/restic-password.txt
  aws-access-key-id:
    file: ./secrets/aws-access-key-id.txt
  aws-secret-access-key:
    file: ./secrets/aws-secret-access-key.txt
